### ISSUE TITLE
TcpStream incompatibility: StubbornTcpStream is not Sync

### ISSUE THREAD

**Issue by bemyak** [craftytrickster/stubborn-io#29]
Hi!

I'm trying to replace `TcpStream` with `SubbornTcpStream` in zmq.rs [here](https://github.com/zeromq/zmq.rs/blob/d3ed228d352f123cd0070504adb5c2d82cfec683/src/transport/tcp.rs#L18), but I'm getting an error: `(dyn Iterator<Item = Duration> + std::marker::Send + 'static) cannot be shared between threads safely`

I tried going down the rabbit hole of making it `Sync`, and somehow stumbled upon [tokio::ToSocketAddr](https://github.com/tokio-rs/tokio/blob/e971a5e7d73757f3631738c8e32c94bbd78f8e26/tokio/src/net/addr.rs#L19) being opaque, and I'm unable to proceed further.

Any advice will be greatly appreciated :pray:

**Comment by craftytrickster** [comment]
I will look into it either today or tomorrow. Maybe I need to just add a + Sync bounds to the iterator on my end here.

**Comment by craftytrickster** [comment]
I created a branch, which I published in the associated PR. would you be able to point to my branch in github from your cargo.toml, and see if it compiles correctly?

Additionally, can you please show me the actual code snippet where you are adding StubbornIo, complete with the options? That way I can see if there is anything else that I need to be aware of.

Thanks.

**Comment by bemyak** [comment]
Hi, thank you for working on this!

Unfortunately, it didn't fix the issue. Here's the diff of my changes: https://github.com/zeromq/zmq.rs/compare/master...bemyak:zmq.rs:subborn

The error is pretty confusing:
```
error[E0277]: `(dyn Fn() -> Box<(dyn Iterator<Item = Duration> + std::marker::Send + 'static)> + std::marker::Send + 'static)` cannot be shared between threads safely
   --> src/transport/tcp.rs:27:21
    |
27  |     Ok((make_framed(raw_socket), Endpoint::from_tcp_addr(peer_addr)))
    |         ----------- ^^^^^^^^^^ `(dyn Fn() -> Box<(dyn Iterator<Item = Duration> + std::marker::Send + 'static)> + std::marker::Send + 'static)` cannot be shared between threads safely
    |         |
    |         required by a bound introduced by this call
    |
    = help: the trait `Sync` is not implemented for `(dyn Fn() -> Box<(dyn Iterator<Item = Duration> + std::marker::Send + 'static)> + std::marker::Send + 'static)`, which is required by `StubbornIo<async_rt::tokio::net::TcpStream, (&str, u16)>: Sync`
    = note: required for `Unique<(dyn Fn() -> Box<(dyn Iterator<Item = Duration> + std::marker::Send + 'static)> + std::marker::Send + 'static)>` to implement `Sync`
```

**Comment by craftytrickster** [comment]
I am able to reproduce it as well, currently I am not able to find an easy solution to getting it to work, I will continue to investigate.

**Comment by craftytrickster** [comment]
I posted a new change that in theory should compile and work, but I want to see if I can avoid the mutex if possible.

**Comment by bemyak** [comment]
There's one other small incompatibility:
```
error[E0716]: temporary value dropped while borrowed
  --> src/transport/tcp.rs:20:50
   |
20 |     let raw_socket = StubbornTcpStream::connect((host.to_string().as_str(), port)).await?;
   |                      ----------------------------^^^^^^^^^^^^^^^^-----------------       - temporary value is freed at the end of this statement
   |                      |                           |
   |                      |                           creates a temporary value which is freed while still in use
   |                      argument requires that borrow lasts for `'static`
```

But it's easy to fix now (pass host as String by value), so it's not a big deal.

Thank you for the fix! I'll give it a proper testing soon, to see if zmq is able to recover from connection losses.

**Comment by craftytrickster** [comment]
I hope it works! With respect to the str reference issue you bring up, that is kind of unavoidable, unless I eaergly perform a clone on the ctor arguments as soon as you call "establish". Id prefer not to do a clone if it isn't really needed, which is why the API is in its current state.

-------- Original Message --------

**Comment by bemyak** [comment]
Hmm, not sure if I'm doing something wrong, but it seems that stubborn is unable to re-establish a connection. I have a zmq client, which `PUB`lishes messages, and another one, which is `SUB`scribed to it. I restart the publisher once, and here's what I get:
```
06:46:58 [INFO] Initial connection succeeded.
06:47:03 [ERROR] Disconnect occurred
06:47:03 [INFO] Will perform reconnect attempt #1 in 4.137203725s.
06:47:07 [INFO] Attempting reconnect #1 now.
06:47:07 [INFO] Connection re-established
06:47:37 [ERROR] Disconnect occurred
06:47:37 [INFO] Will perform reconnect attempt #1 in 4.102957762s.
06:47:41 [INFO] Attempting reconnect #1 now.
06:47:41 [INFO] Connection re-established
06:48:12 [ERROR] Disconnect occurred
06:48:12 [INFO] Will perform reconnect attempt #1 in 3.899307349s.
06:48:15 [INFO] Attempting reconnect #1 now.
06:48:15 [INFO] Connection re-established
…
```

The connection seems to time-out in 30s after being re-established :thinking:

**Comment by craftytrickster** [comment]
This evening I'll clone your project and see what's going on. Thank you for the error logs.

**Comment by craftytrickster** [comment]
Thanks for help here, published new crate version with the sync change.
